### ISSUE TITLE
The maps dont work on Android Pie

### ISSUE THREAD

**Issue by luiiss997** [shivpujan12/LocationPicker#2]
The maps dont show it in Android 29 (Pie), and the location search dont load the request, I have my own key of API Google places and maps. Everything else its ok. I will be thankful so much if you help me. Sorry for the bad english, regards from Mexico.

**Comment by monicarenas4** [comment]
I had the same problem and I solved by adding my credit card into the Google Platform, you do not need to pay anything, you can access for free during 1 year, after that you pay according to your project. **Remember to active all the API related to the Location.**

**Comment by shivpujan12** [comment]
You need to have a valid api key for proper working of the library. @luiiss997
